# Copyright (c) PyPTO Contributors.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# -----------------------------------------------------------------------------------------------------------

"""TMARB orchestration pseudocode generator.

Produces human-readable C++-like pseudocode showing what a TMARB runtime
consumer would generate from a ``SonataScheduleContract``.

The output uses TMARB API surface (``pto_orchestration_api.h``) but is
NOT compilable — it exists solely to prove structural mapping completeness.
"""

from __future__ import annotations

from typing import Any

from ..schedule import (
    ArgDirection,
    ScheduledRegion,
    ScopeMode,
    SonataScheduleContract,
)


def generate_pseudocode(schedule: SonataScheduleContract) -> str:
    """Generate C++-like pseudocode for a schedule contract.

    The pseudocode shows the orchestration body with ``PTO2_SCOPE`` blocks,
    ``rt_submit_*_task`` calls, and ``Arg::add_*`` operations.
    """
    lines: list[str] = []
    _write_header(schedule, lines)

    for region in schedule.regions:
        _write_region(region, lines, indent=1)

    lines.append(f"{_indent(1)}rt_orchestration_done();")
    lines.append("}")
    return "\n".join(lines)


def _write_header(schedule: SonataScheduleContract, lines: list[str]) -> None:
    lines.append("// Generated by Sonata TMARB pseudocode generator")
    lines.append(f"// Source: sonata_schedule.json (fp: {schedule.fingerprint})")
    lines.append(f"// Schema version: {schedule.schema_version}")
    lines.append("")
    lines.append('extern "C" void aicpu_orchestration_entry(const ChipStorageTaskArgs& orch_args) {')


def _write_region(region: ScheduledRegion, lines: list[str], indent: int = 1) -> None:
    if region.kind == "dynamic":
        lines.append(f"{_indent(indent)}// ── Region {region.region_id} (dynamic) ──")
        lines.append(f"{_indent(indent)}PTO2_SCOPE() {{")
        lines.append(f"{_indent(indent)}}}")
        return

    mode_str = "PTO2ScopeMode::MANUAL" if region.scope_mode == ScopeMode.MANUAL else ""
    mode_comment = " (MANUAL)" if region.scope_mode == ScopeMode.MANUAL else ""
    lines.append(f"{_indent(indent)}// ── Region {region.region_id} (static{mode_comment}) ──")
    if mode_str:
        lines.append(f"{_indent(indent)}PTO2_SCOPE({mode_str}) {{")
    else:
        lines.append(f"{_indent(indent)}PTO2_SCOPE() {{")

    for task in region.tasks:
        _write_task(task, lines, indent + 1)

    lines.append(f"{_indent(indent)}}}")


def _write_task(task: Any, lines: list[str], indent: int = 1) -> None:
    task_var = f"params_t{task.task_id}"
    is_aiv = task.core_type == "aiv"
    is_mixed = task.mixed_kernels is not None
    lines.append(f"{_indent(indent)}// Task {task.task_id}: {task.kernel_identity} "
                 f"(func_id={task.func_id}, core={task.core_type})")
    lines.append(f"{_indent(indent)}Arg {task_var};")

    dir_to_api = {
        ArgDirection.INPUT: "add_input",
        ArgDirection.OUTPUT: "add_output",
        ArgDirection.INOUT: "add_inout",
        ArgDirection.OUTPUT_EXISTING: "add_output",
        ArgDirection.NO_DEP: "add_no_dep",
        ArgDirection.SCALAR: "add_scalar",
    }
    for arg in task.args:
        api_name = dir_to_api.get(arg.direction, "add_input")
        val = f'"{arg.arg_identity}"'
        lines.append(f"{_indent(indent)}{task_var}.{api_name}({val});")

    if is_mixed:
        mk = task.mixed_kernels
        lines.append(f"{_indent(indent)}MixedKernels mk{{{mk.aic_func_id}, {mk.aiv_func_id}, "
                     f"{mk.dual_aiv_func_id if mk.dual_aiv_func_id is not None else 'INVALID_KERNEL_ID'}}};")
        submit = f"rt_submit_task(mk, {task_var})"
    elif is_aiv:
        submit = f"rt_submit_aiv_task({task.func_id}, {task_var})"
    else:
        submit = f"rt_submit_aic_task({task.func_id}, {task_var})"

    lines.append(f"{_indent(indent)}TaskOutputTensors t{task.task_id}_outs = {submit};")


def _indent(level: int) -> str:
    return "    " * level


__all__ = [
    "generate_pseudocode",
]
